Repository opnsense/plugins, pull requests merged in 2018-10, with the labels that each got.

#895 add backup api; closes #865
  sysutils/api-backup/Makefile
  sysutils/api-backup/pkg-descr
  sysutils/api-backup/src/opnsense/mvc/app/controllers/OPNsense/Backup/Api/BackupController.php
  sysutils/api-backup/src/opnsense/mvc/app/models/OPNsense/Backup/ACL/ACL.xml
Labels: enhancement

#893 Problem with multiple Upstream servers
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/upstream.conf
Labels: bug

#891 www/nginx: import naxsi core rules into configuration
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/IndexController.php
  www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
  www/nginx/src/opnsense/scripts/nginx/naxsi_rule_download.php
  www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/upstream.conf
Labels: enhancement

#904 www/nginx: guard loop parameter with an if
  www/nginx/src/opnsense/scripts/nginx/setup.php
Labels: bug

#914 www/nginx: fix rule 19 issue
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/ruleset.conf
Labels: bug

#925 nginx header problems
  www/nginx/Makefile
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
Labels: bug

#943 OSPFv2: key id
  net/frr/Makefile
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
Labels: feature
