Repository opnsense/plugins, pull requests merged in 2018-05, with the labels that each got.

#659 sysutils/nut: little tweaks
  sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/Api/ServiceController.php
  sysutils/nut/src/opnsense/mvc/app/views/OPNsense/Nut/index.volt
  sysutils/nut/src/opnsense/service/conf/actions.d/actions_nut.conf
Labels: bug, enhancement

#668 FreeRadius: Fix help message on User dialog
  net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
Labels: bug

#579 net/haproxy: release 2.7
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: enhancement

#669 security/acme-client: Add the ability to specify domain key length
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Labels: enhancement

#680 net/haproxy: support for cookie-based persistence
  net/haproxy/Makefile
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M2_7_0.php
  net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: enhancement

#682 security/acme-client: fix node no longer exists error
  security/acme-client/Makefile
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Labels: enhancement

#695 net/haproxy: fix validation for source address fields
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
Labels: bug
