Repository opnsense/plugins, pull requests merged in 2018-11, with the labels that each got.

#956 security/softether: new plugin
  security/softether/Makefile
  security/softether/pkg-descr
  security/softether/src/etc/inc/plugins.inc.d/softether.inc
  security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/Api/GeneralController.php
  security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/Api/ServiceController.php
  security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/GeneralController.php
  security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/forms/general.xml
  security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/ACL/ACL.xml
  security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/General.php
  security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/General.xml
  security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/Menu/Menu.xml
  security/softether/src/opnsense/mvc/app/views/OPNsense/Softether/general.volt
  security/softether/src/opnsense/scripts/OPNsense/Softether/setup.sh
  security/softether/src/opnsense/service/conf/actions.d/actions_softether.conf
  security/softether/src/opnsense/service/templates/OPNsense/Softether/+TARGETS
  security/softether/src/opnsense/service/templates/OPNsense/Softether/softether_server
Labels: feature

#970 net/haproxy: more features for release 2.10
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/IndexController.php
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAcl.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogGroup.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogUser.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Menu/Menu.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M2_6_0.php
  net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: feature

#930 www/nginx: streams support, fix config store
  www/nginx/Makefile
  www/nginx/pkg-descr
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/IndexController.php
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/ipacl.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/sni_hostname_map.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/streamserver.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.php
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
  www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/logs.volt
  www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
  www/nginx/src/opnsense/scripts/nginx/setup.php
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/ipacl.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/nginx.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf
  www/nginx/src/opnsense/www/js/nginx/dist/bundle.js
  www/nginx/src/opnsense/www/js/nginx/dist/configuration.js
  www/nginx/src/opnsense/www/js/nginx/dist/logviewer.js
  www/nginx/src/opnsense/www/js/nginx/src/controller/KeyValueMapField.js
  www/nginx/src/opnsense/www/js/nginx/src/controller/KeyValueMapFieldEntry.js
  www/nginx/src/opnsense/www/js/nginx/src/models/IPACLCollection.js
  www/nginx/src/opnsense/www/js/nginx/src/models/IPACLModel.js
  www/nginx/src/opnsense/www/js/nginx/src/models/SNIHostnameUpstreamCollection.js
  www/nginx/src/opnsense/www/js/nginx/src/models/SNIHostnameUpstreamModel.js
  www/nginx/src/opnsense/www/js/nginx/src/models/UpstreamCollection.js
  www/nginx/src/opnsense/www/js/nginx/src/nginx_config.js
  www/nginx/src/opnsense/www/js/nginx/webpack.conf.js
Labels: bug, feature

#998 net-mgmt/zabbix-agent: release 1.4
  net-mgmt/zabbix-agent/Makefile
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/Api/SettingsController.php
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/IndexController.php
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/dialogAlias.xml
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/dialogUserparameter.xml
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/settings.xml
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml
  net-mgmt/zabbix-agent/src/opnsense/mvc/app/views/OPNsense/ZabbixAgent/index.volt
  net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agentd.conf
Labels: feature

#1003 net/haproxy: 3rd feature set for release 2.10
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/IndexController.php
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogCpu.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: feature

#1009 www/nginx: add request size limitation, satisfy and fix some generic bugs
  www/nginx/pkg-descr
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
  www/nginx/src/opnsense/www/js/nginx/src/nginx_config.js
Labels: bug, feature

#1011 www/nginx: add fields for proxy server
  www/nginx/Makefile
  www/nginx/pkg-descr
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
Labels: feature

#1024 net/haproxy: Release 2.11
  net/haproxy/Makefile
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: bug

#1035 Check if charset is defined
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
Labels: bug
