Repository opnsense/plugins, pull requests merged in 2018-07, with the labels that each got.

#712 security/acme-client: add support to multiple dns api providers
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Labels: enhancement

#725 net/haproxy: bring back tokenizer
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
Labels: bug

#731 dns/bind: acl, forwards, menu item
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/Api/AclController.php
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/GeneralController.php
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindAcl.xml
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/general.xml
  dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Acl.php
  dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Acl.xml
  dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/General.xml
  dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Menu/Menu.xml
  dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
  dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
Labels: enhancement

#742 www/nginx: some bugfixes; add a rule for the upcoming naxsi release; add restart action to acme
  .gitignore
  net/haproxy/Makefile
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
  www/nginx/Makefile
  www/nginx/src/etc/nginx/views/opnsense_error_404.html
  www/nginx/src/etc/nginx/views/opnsense_server_error.html
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/php-www.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/ruleset.conf
Labels: bug, enhancement

#762 www/nginx: add HTTPS backends
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/scripts/nginx/setup.php
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
Labels: enhancement
