Repository opnsense/plugins, pull requests merged in 2018-12, with the labels that each got.

#1047 net/haproxy: Add support for HTTP/2
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: feature

#1054 security/acme-client: Add support for ACME DNS
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Labels: feature

#1042 Update AcmeClient.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#1051 www/nginx: add proxy protocol support and improve whitelist handling of WAF
  www/nginx/pkg-descr
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/streamserver.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf
Labels: bug, feature

#1048 www/c-icap: add customized virus found page
  www/c-icap/Makefile
  www/c-icap/src/opnsense/scripts/OPNsense/CICAP/setup.sh
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/+TARGETS
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/VIRUS_FOUND
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/VIR_MODE_HEAD
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/VIR_MODE_PROGRESS
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/VIR_MODE_TAIL
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/VIR_MODE_VIRUS_FOUND
  www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/c-icap.conf
Labels: feature

#1067 www/nginx: fix basic auth acl permission error
  www/nginx/pkg-descr
  www/nginx/src/opnsense/scripts/nginx/setup.php
Labels: bug

#1069 mail/postfix: allow tls wrapper mode
  mail/postfix/Makefile
  mail/postfix/pkg-descr
  mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
  mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
  mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
Labels: feature

#1070 WIP: www/nginx: add njs script to detect MitM attacks on TLS connections
  www/nginx/src/opnsense/scripts/nginx/ngx_functions.js
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/nginx.conf
Labels: feature

#1075 www/nginx: backend performance improvements
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
  www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/AccessLogParser.php
  www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/StreamAccessLogParser.php
Labels: bug

#1086 www/nginx: allow to generate the fingerprint database from config.xml
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/IndexController.php
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/tls_fingerprint.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
  www/nginx/src/opnsense/scripts/nginx/setup.php
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
  www/nginx/src/opnsense/www/js/nginx/dist/configuration.min.js
  www/nginx/src/opnsense/www/js/nginx/src/nginx_config.js
Labels: feature

#1087 www/nginx: advanced authentication: allow to use an own auth server, cleanup config
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
  www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
  www/nginx/src/opnsense/scripts/nginx/ngx_auth.php
  www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
Labels: feature

#1085 dns/bind: Add duck duck go
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dnsbl.xml
  dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
  dns/bind/src/opnsense/service/templates/OPNsense/Bind/+TARGETS
  dns/bind/src/opnsense/service/templates/OPNsense/Bind/duckduckgo.db
  dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
Labels: feature

#1093 www/nginx global error log viewer tab
  www/nginx/pkg-descr
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
  www/nginx/src/opnsense/scripts/nginx/read_log.php
  www/nginx/src/opnsense/www/js/nginx/dist/configuration.min.js
  www/nginx/src/opnsense/www/js/nginx/dist/logviewer.min.js
  www/nginx/src/opnsense/www/js/nginx/src/controller/LogCategoryList.js
  www/nginx/src/opnsense/www/js/nginx/src/controller/SingleTab.js
  www/nginx/src/opnsense/www/js/nginx/src/templates/single_tab.html
Labels: feature

#1098 www/nginx: TLS fingerprint log API, phpdoc
  www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
  www/nginx/src/opnsense/scripts/nginx/read_log.php
  www/nginx/src/opnsense/scripts/nginx/tls_ua_fingerprint.php
  www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf
Labels: feature
