Repository opnsense/plugins, pull requests merged in 2019-09, with the labels that each got.

#1460 FRR/ospf: demote/promote carp when no neighbors are found
  net/frr/src/etc/rc.carp_service_status.d/carp_frr_ospf
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/syslog-ng-frr-events.conf
Labels: feature

#1455 AcmeClient support cert upload via sftp
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ActionsController.php
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Process.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SSHKeys.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpClient.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpUploader.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Utils.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php
  security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf
Labels: feature

#1491 Add dns_opnsense.sh and support to the ACME Client
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dns_opnsense.sh
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
Labels: feature

#1458 net/haproxy: Update cache to support HAProxy 2.0 option
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: feature

#1493 mail/postfix: allow setting of supported IP protocols
  mail/postfix/Makefile
  mail/postfix/pkg-descr
  mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
  mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
  mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
Labels: feature

#1512 Add checkbox to disable dormant mode at startup
  security/tor/Makefile
  security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/general.xml
  security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/General.xml
  security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc
Labels: bug, feature

#1510 net/frr: Issue #1509. Fixing issue with net/frr BGP diagnostics summary tab
  net/frr/src/opnsense/scripts/quagga/quagga.rb
Labels: bug

#1508 net/frr: add some OSPFv3 features and fixes
  net/frr/Makefile
  net/frr/pkg-descr
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6Interface.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
Labels: bug, feature
