Repository opnsense/plugins, pull requests merged in 2019-08, with the labels that each got.

#1443 net/wireguard: add gateway support for PBR via PF
  net/wireguard/Makefile
  net/wireguard/pkg-descr
  net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
  net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
  net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
Labels: feature

#1350 security/acme-client: Add Support for netcup DNS API
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Labels: feature, upstream

#1442 net/haproxy: Initial support for HAProxy cache
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Menu/Menu.xml
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: feature

#1439 net/haproxy: Change http-reuse default
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
Labels: feature

#1431 dns/bind: small improvements for zone management
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindDomain.xml
  dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindRecord.xml
  dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
  dns/bind/src/opnsense/service/templates/OPNsense/Bind/domain.db
Labels: feature

#1427 www/nginx TLS logrotate
  www/nginx/Makefile
  www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
  www/nginx/src/opnsense/scripts/nginx/tls_ua_fingerprint.php
  www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf
Labels: bug

#1409 www/nginx, net/frr: update lodash
  net/frr/src/opnsense/www/js/quagga/lodash.js
  www/nginx/src/opnsense/www/js/nginx/dist/README.md
  www/nginx/src/opnsense/www/js/nginx/lib/lodash.min.js
  www/nginx/src/opnsense/www/js/nginx/npm-shrinkwrap.json
  www/nginx/src/opnsense/www/js/nginx/package.json
Labels: bug
