Repository opnsense/plugins, pull requests merged in 2020-11, with the labels that each got.

#2107 dns/bind: small quality of life improvements
  dns/bind/Makefile
  dns/bind/pkg-descr
  dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Acl.xml
  dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
Labels: bug, feature

#2119 security/acme-client: release 2.1
  security/acme-client/Makefile
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNsupdate.php
Labels: bug

#2120 security/acme-client: add support for deSEC.io API
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsDedyn.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature
