Repository opnsense/plugins, pull requests merged in 2022-07, with the labels that each got.

#3049 acme-client: Add Active24 challenge type
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsActive24.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#3043 Re-order function parameters due to PHP8 deprecation notice
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.php
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
Labels: cleanup

#2888 security/acme-client: Add Simply.com (used to be UnoEuro)
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsSimply.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature, upstream
