Repository opnsense/plugins, pull requests merged in 2023-02, with the labels that each got.

#3301 emulators/qemu-guest-agent: release 1.2
  emulators/qemu-guest-agent/Makefile
  emulators/qemu-guest-agent/pkg-descr
Labels: cleanup

#3226 net/haproxy: fix HAProxy SSL preferences in healthchecks
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Labels: bug

#3318 security/acme: support cert upload to Palo Alto Firewall, closes #3289
  security/acme-client/Makefile
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmePanos.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#3319 security/acme: Add JD Cloud API dns challenge type, closes #3315
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsJd.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#3320 security/acme: minor lighty config fixes
  security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/lighttpd-acme-challenge.conf
Labels: cleanup

#3309 sysutils/api-backup: add json download functionality
  sysutils/api-backup/Makefile
  sysutils/api-backup/pkg-descr
  sysutils/api-backup/src/opnsense/mvc/app/controllers/OPNsense/Backup/Api/BackupController.php
Labels: feature
