Repository opnsense/plugins, pull requests merged in 2023-08, with the labels that each got.

#3517 security/acme: expose new values for Proxmox VE deployhook, closes #3516
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeProxmoxve.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: bug

#3504 security/acme-client: Add IPv64.net support
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsIpv64.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#3527 net/relayd - sync with OpenBSD
  net/relayd/Makefile
  net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/Api/StatusController.php
  net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Migrations/M1_0_5.php
  net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Relayd.xml
  net/relayd/src/opnsense/service/templates/OPNsense/Relayd/relayd.conf
Labels: cleanup

#3533 Add desec service provider to ddclient OPnsense backend
  dns/ddclient/src/opnsense/scripts/ddclient/lib/account/dyndns2.py
Labels: feature

#3537 NET/FRR: Added OSPFv3 firewall rules for floating ruleset / optional rules.
  net/frr/src/etc/inc/plugins.inc.d/frr.inc
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/general.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml
Labels: feature
