Repository opnsense/plugins, pull requests merged in 2024-01, with the labels that each got.

#3742 Update max value forms display text for acme client
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
Labels: cleanup

#3730 net/frr - add "soft-reconfiguration inbound" neighbor option
  net/frr/Makefile
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Labels: feature

#3749 security/acme-client: small refactoring and bugfix for #3745
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
Labels: bug

#3752 Fix crash on ACME automations
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
Labels: bug

#3751 security/acme-client: release 4.0 [only for 24.1]
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsAurora.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsConoha.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsConstellix.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsExoscale.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsInternetbs.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsPointhq.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsRackspace.php
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsRage4.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_0_0.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_1_0.php
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
Labels: feature

#3694 net/haproxy: release 4.2 [only for 24.1]
  net/haproxy/Makefile
  net/haproxy/pkg-descr
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFcgi.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMapfile.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalSettings.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
  net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/maintenanceCronjobs.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
  net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M4_1_0.php
  net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/__init__.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/cmds.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/conn.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/const.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/tests/__init__.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/tests/test_cmds.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/tests/test_conn.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/setup.sh
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/socketCommand.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/syncCerts.py
  net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/updateOcsp.sh
  net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
  net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/rc.conf.d
Labels: feature

#3770 net/frr: Add plain password authentication to OSPF
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
Labels: feature
