Repository opnsense/plugins, pull requests merged in 2024-09, with the labels that each got.

#4209 www/caddy: Refactor general.volt to base_tabs, Update DNS Providers
  www/caddy/Makefile
  www/caddy/pkg-descr
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/GeneralController.php
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/authprovider.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dnsprovider.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dynamicdns.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/logsettings.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/diagnostics.volt
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeDnsProvider
Labels: feature, cleanup

#4211 www/caddy: Refactor Caddyfile template to make it more dry
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: cleanup

#4213 www/caddy: Remove old custom migration scripts
  www/caddy/pkg-descr
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Migrations/M1_1_3.php
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Migrations/M1_1_8.php
Labels: cleanup

#4237 www/caddy: Fix typo in "TlsInsecureSkipVerify" condition
  www/caddy/Makefile
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: bug

#4234 www/caddy: Fix api endpoints in widgets via lint-acl
  www/caddy/src/opnsense/www/js/widgets/Metadata/Caddy.xml
Labels: cleanup

#3566 security/acme-client: Add Support for Lima-City DNS API
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsLimacity.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature, upstream
