Repository opnsense/plugins, pull requests merged in 2024-11, with the labels that each got.

#4323 www/caddy: Remove default route from layer4 since its obsolete
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: cleanup

#4325 www/caddy: Add Layer4 openvpn, winbox and quic matcher
  www/caddy/Makefile
  www/caddy/pkg-descr
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Layer4Controller.php
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4Openvpn.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/layer4.volt
  www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
Labels: feature

#4334 www/caddy: Fix access on both wildcard and subdomain causing error
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: bug

#4346 security/wazuh-agent: implement options to change server ports
  security/wazuh-agent/src/opnsense/mvc/app/controllers/OPNsense/WazuhAgent/forms/settings.xml
  security/wazuh-agent/src/opnsense/mvc/app/models/OPNsense/WazuhAgent/WazuhAgent.xml
  security/wazuh-agent/src/opnsense/service/templates/OPNsense/WazuhAgent/ossec.conf
Labels: feature

#4348 net/ndproxy: Add os-ndproxy plugin
  net/ndproxy/Makefile
  net/ndproxy/pkg-descr
  net/ndproxy/src/etc/inc/plugins.inc.d/ndproxy.inc
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/Api/GeneralController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/Api/ServiceController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/GeneralController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/Api/GeneralController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/Api/ServiceController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/GeneralController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/general.xml
  net/ndproxy/src/opnsense/mvc/app/models/OPNsense/Ndproxy/ACL/ACL.xml
  net/ndproxy/src/opnsense/mvc/app/models/OPNsense/Ndproxy/Menu/Menu.xml
  net/ndproxy/src/opnsense/mvc/app/models/OPNsense/Ndproxy/Ndproxy.php
  net/ndproxy/src/opnsense/mvc/app/models/OPNsense/Ndproxy/Ndproxy.xml
  net/ndproxy/src/opnsense/mvc/app/views/OPNsense/Ndproxy/general.volt
  net/ndproxy/src/opnsense/service/conf/actions.d/actions_ndproxy.conf
  net/ndproxy/src/opnsense/service/templates/OPNsense/Ndproxy/+TARGETS
  net/ndproxy/src/opnsense/service/templates/OPNsense/Ndproxy/rc.conf.d/ndproxy
Labels: feature

#4365 www/caddy: Refactor certificate extraction to Trust model
  www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
Labels: cleanup

#4369 www/caddy: Add h2c protocol to handler
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: feature
