Repository opnsense/plugins, pull requests merged in 2024-12, with the labels that each got.

#4372 www/caddy: widgets, hide unused certs, improve error handling
  www/caddy/pkg-descr
  www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js
  www/caddy/src/opnsense/www/js/widgets/CaddyDomain.js
  www/caddy/src/opnsense/www/js/widgets/Metadata/Caddy.xml
Labels: cleanup

#4376 net/ndproxy: Delete duplicate files
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/Api/GeneralController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/Api/ServiceController.php
  net/ndproxy/src/opnsense/mvc/app/controllers/OPNsense/Ndproxy/forms/GeneralController.php
Labels: cleanup

#4331 net/haproxy: Fix "not all arguments converted during string formatting" in cert_sync
  net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
Labels: bug

#4385 www/caddy: Fix wildcard certificate extraction for widget
  www/caddy/Makefile
  www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_diagnostics.py
Labels: bug

#4375 net/mdns-repeater: Modernize plugin code; Add blocklist support (contributed by Kodehyrden)
  net/mdns-repeater/Makefile
  net/mdns-repeater/pkg-descr
  net/mdns-repeater/src/etc/inc/plugins.inc.d/mdnsrepeater.inc
  net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/Api/ServiceController.php
  net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/forms/general.xml
  net/mdns-repeater/src/opnsense/mvc/app/models/OPNsense/MDNSRepeater/MDNSRepeater.xml
  net/mdns-repeater/src/opnsense/mvc/app/views/OPNsense/MDNSRepeater/index.volt
  net/mdns-repeater/src/opnsense/service/conf/actions.d/actions_mdnsrepeater.conf
  net/mdns-repeater/src/opnsense/service/templates/OPNsense/MDNSRepeater/mdnsrepeater
Labels: feature, cleanup

#4390 www/caddy: Fix redirect regression
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: bug

#4405 www/caddy: Add missing changelog for 1.7.6
  www/caddy/pkg-descr
Labels: cleanup

#4328 security/acme-client: Add support for MyDNS.JP DNS API
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsMydnsjp.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#4389 security/acme-client: Add fornex API dns challenge type
  security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsFornex.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#4419 www/squid: Squid syslog corrections
  www/squid/src/etc/inc/plugins.inc.d/squid.inc
  www/squid/src/opnsense/service/templates/OPNsense/Syslog/local/squid_access.conf
Labels: cleanup
