Repository opnsense/plugins, pull requests merged in 2024-10, with the labels that each got.

#4271 security/acme-client: release 4.6
  security/acme-client/Makefile
  security/acme-client/pkg-descr
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
Labels: bug

#4281 www/caddy: Complete Layer4 routing feature
  www/caddy/pkg-descr
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
Labels: feature

#4291 Correct minor issues in OSPF6
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
Labels: bug

#4285 net/frr - Routing: BFD - add multihop support for IPv4.
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBFDNeighbor.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BFD.php
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BFD.xml
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/bfdd.conf
Labels: feature

#4228 security/etpro-telemetry: Lower logging priority
  security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/send_telemetry.py
Labels: cleanup
