Repository opnsense/plugins, pull requests merged in 2025-04, with the labels that each got.

#4635 net/frr: Fix wrong route redistribution option for ospf (bgp missing)
  net/frr/Makefile
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
Labels: cleanup

#4631 www/caddy: Change and fix ACL privileges
  www/caddy/pkg-descr
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/ACL/ACL.xml
Labels: bug

#4636 www/caddy: Also add log file pattern to ACL
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/ACL/ACL.xml
Labels: cleanup

#4637 www/caddy: Remove CaddyCertificate.js widget in favor of using the default core provided widget
  www/caddy/pkg-descr
  www/caddy/src/etc/ssl/ext_sources/caddy.conf
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/DiagnosticsController.php
  www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_diagnostics.py
  www/caddy/src/opnsense/service/conf/actions.d/actions_caddy.conf
  www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js
  www/caddy/src/opnsense/www/js/widgets/Metadata/Caddy.xml
Labels: cleanup

#4634 www/caddy: Cleanup volt templates
  www/caddy/pkg-descr
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Layer4Controller.php
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/ReverseProxyController.php
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/layer4.volt
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
Labels: feature, cleanup

#4646 www/caddy: Show only wildcard domains in subdomain selection
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
Labels: cleanup

#4644 www/caddy: Revise dns providers for caddy-v2.10.0
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
Labels: upstream, dependencies

#4657 security/wazuh-agent: make agent_name configurable
  security/wazuh-agent/src/opnsense/mvc/app/controllers/OPNsense/WazuhAgent/forms/settings.xml
  security/wazuh-agent/src/opnsense/mvc/app/models/OPNsense/WazuhAgent/WazuhAgent.xml
  security/wazuh-agent/src/opnsense/service/templates/OPNsense/WazuhAgent/ossec.conf
Labels: feature
