Repository opnsense/plugins, pull requests merged in 2025-01, with the labels that each got.

#4442 www/caddy: Some small UX tweaks
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
Labels: cleanup

#4439 www/caddy: Refactor caddy.inc and add syslog function
  www/caddy/Makefile
  www/caddy/pkg-descr
  www/caddy/src/etc/inc/plugins.inc.d/caddy.inc
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Menu/Menu.xml
Labels: cleanup

#4450 net/frr - style cleanup and unify forms
  net/frr/Makefile
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BfdController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/GeneralController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/ServiceController.php
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bfd.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/general.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/rip.volt
Labels: cleanup

#4479 security/acme-client: fix export of ca certs for SFTP upload automation
  security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php
Labels: bug

#4494 net/frr: Integrate layout_partials/base_bootgrid_table
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BfdController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BgpController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/IsisController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Ospf6Controller.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/OspfController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/StaticController.php
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBFDNeighbor.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPASPath.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPCommunityLists.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPPeergroups.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPPrefixLists.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPRouteMaps.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6Interface.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6Network.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6PrefixLists.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6RouteMaps.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFNetwork.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFPrefixLists.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFRouteMaps.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditSTATICRoute.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/general.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/isis.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf6.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/rip.xml
  net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/static.xml
  net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/Menu/Menu.xml
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bfd.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
  net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/static.volt
  net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr
Labels: cleanup

#4507 Include ClouDNS as DNS Provider in Caddy
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeDnsProvider
Labels: feature
