Repository opnsense/plugins, pull requests merged in 2025-05, with the labels that each got.

#4680 www/caddy: Add Request Matcher option to Access List
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: feature

#4673 www/caddy: Change template generation of wildcard+subdomain pattern to support ECH and mTLS
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: feature, cleanup

#4691 www/caddy: Remove DNS Provider subsystem except cloudflare in favor of global custom config file
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
  www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
  www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeDnsProvider
Labels: cleanup

#4703 www/caddy: Add changelogs and bump plugin to version 2.0.0
  www/caddy/Makefile
  www/caddy/pkg-descr
Labels: cleanup

#4692 security/acme-client: reload www/caddy automation added
  security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdReloadCaddy.php
  security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Labels: feature

#4725 www/caddy: Fix active health check in template
  www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Labels: cleanup
